import QRCodeImage from "@/components/QRCodeImage";
import Head from "next/head";
import type { QRCodeRenderersOptions } from "qrcode";
import { useMemo } from "react";

export default function Home() {
  const qrOptions = useMemo<QRCodeRenderersOptions>(
    () => ({
      margin: 0,
      color: {
        light: "#00000000",
        dark: "ffffff",
      },
    }),
    []
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-lightGray">
        <div className="flex w-72 flex-col items-center gap-4 rounded-2xl bg-white p-4 pb-10 shadow-lg shadow-slate-300">
          <section className="relative overflow-hidden rounded-xl bg-blue-500 p-14 before:absolute before:-left-1/3 before:-top-1/2 before:h-64 before:w-64 before:rounded-full before:bg-blue-200 before:opacity-10 after:absolute after:-bottom-2/3 after:-right-1/2 after:h-64 after:w-64 after:rounded-full after:bg-blue-200 after:opacity-10">
            <QRCodeImage
              data="https://www.frontendmentor.io/"
              alt="FrontEnd Mentor QR"
              size={144}
              qrOptions={qrOptions}
            />
          </section>
          <h4 className="text-center font-outfit text-xl font-bold text-darkBlue">
            Improve your front-end skills by building projects
          </h4>
          <p className="text-center font-outfit text-base text-grayishBlue">
            Scan the QR Code to visit Frontend Mentor and take your coding
            skills to the next level
          </p>
        </div>
      </main>
    </>
  );
}
